### ISSUE TITLE
error on launch

### ISSUE THREAD

**Issue by drewauff** [peterjschroeder/googlit#1]
Traceback (most recent call last):
  File "/usr/local/bin/googlit", line 6, in <module>
    from xdg.BaseDirectory import *
ModuleNotFoundError: No module named 'xdg.BaseDirectory'

**Comment by peterjschroeder** [comment]
pip3 install pyxdg

If you pip3 install git+https://github.com/peterjschroeder/googlit.git

it will pull in all the dependencies.

**Comment by drewauff** [comment]
Awesoem!! Works Now, Thankyou!
